### ISSUE TITLE
why not complete delete and other functional?

### ISSUE THREAD

**Issue by domingogogo** [react-native-hero/qiniu#1]
Hi developer, thanks so much you can make it up. but i have some questions.  I saw qiniu official website has other functions. but this plugin can't include it. likes delete function. hope you can finish that and make this plugin better to better.

**Comment by musicode** [comment]
I just need upload method, if you need delete method, I will add it for you.

**Comment by domingogogo** [comment]
> I just need upload method, if you need delete method, I will add it for you.

thank you for your reply. As you say. I really need delete method. Please.
Best Regards!

**Comment by musicode** [comment]
I don't see any information about delete method of qiniu official ios and android sdk, maybe you should delete file by https api?

**Comment by domingogogo** [comment]
> I don't see any information about delete method of qiniu official ios and android sdk, maybe you should delete file by https api?

Alright. thanks. That means I need to require backend add it. thank you for your help
